### ISSUE TITLE
set virtual port baud rate to 2000000

### ISSUE THREAD

**Issue by eddylai** [kobolt/usb-can#2]
from their website it said the port baud rate should be set to 2000000
https://github.com/SeeedDocument/USB-CAN_Analyzer/blob/master/res/USB-CAN%20software%20and%20drive(v7.10)/Document/USB%20(Serial%20port)%20to%20CAN%20protocol%20defines.pdf
I have a CAN device with 500k data rate, and i tried to set the virtual com port's baud rate to 2000000 bps but failed,
is this because Linux not support buad rate like that?

**Comment by kobolt** [comment]
It's been a while since I used this adapter so I don't remember the exact details. But I think that the adapter could run at several different baud rates, including the un-standard 2000000 rate. Linux does support weird/un-standard baud rates through the termios2 structure, that's why it's used in this program. What kind of error are you seeing? Is the ioctl() call failing perhaps? Also, what Linux kernel are you using?

**Comment by kobolt** [comment]
I had a chance to test this, but I can see no problem and it dumps data as expected:
```
./canusb -d /dev/ttyUSB2 -b 2000000 -s 500000
4147542.421951 Frame ID: 0041, Data: 80
4147543.021301 Frame ID: 0041, Data: c0
4147543.261301 Frame ID: 0001, Data: 1c cf 2a 37 5d 9b 94 a5
4147543.621682 Frame ID: 0041, Data: 80
4147544.221688 Frame ID: 0041, Data: c0
4147544.261364 Frame ID: 0001, Data: 1c cf a8 d5 5d 9b 94 a6
4147544.822070 Frame ID: 0041, Data: 80
4147545.261554 Frame ID: 0001, Data: 1c ce 79 65 5d 9b 94 a7
4147545.421364 Frame ID: 0041, Data: c0
4147546.021428 Frame ID: 0041, Data: 80
4147546.261554 Frame ID: 0001, Data: 1c cf 14 d9 5d 9b 94 a8
```

**Comment by kobolt** [comment]
Closing this due to no feedback.
